import React,{useEffect,useState}from "react";
import Layout from "../components/Layout.jsx";
import { Field,inputCls,PrimaryButton } from "../components/FormBits.jsx";
import api from "../api";
import {useAuth} from "../context/AuthContext.jsx";

export default function Settings({mainAdminOnly=false}){
 const {user}=useAuth();
 const [smtp,setSmtp]=useState({smtp_google_account:"",smtp_app_password:"",smtp_from_email:"",smtp_display_name:"Donation Tracker"});
 const [sola,setSola]=useState({sola_api_key:"",sola_ifields_key:"",sola_environment:"production",sola_ifields_version:"2.9.2109.2701",lock_main_admin:false});
 const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [testEmail,setTestEmail]=useState("");
 const [mapping,setMapping]=useState({firstName:"",lastName:"",phone:"",email:"",group:"",active:""}); const [sheetRows,setSheetRows]=useState([]); const [headers,setHeaders]=useState([]);
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState("");
 const isMain=!!user?.isMainAdmin;
 useEffect(()=>{if(isMain&&mainAdminOnly){api.get("/admin/settings").then(r=>{setSmtp(x=>({...x,...r.data}));setSola(x=>({...x,...r.data}))}).catch(()=>{});if(!window.XLSX){const sc=document.createElement("script");sc.src="https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js";sc.onload=()=>{};document.head.appendChild(sc);}},[isMain,mainAdminOnly]);
 async function saveAll(e){e.preventDefault();setError("");try{await api.put("/admin/settings",{...smtp,...sola});setStatus("Settings saved.");}catch(e){setError(e.response?.data?.error||"Could not save settings")}}
 async function sendTest(){setError("");try{await api.post("/admin/test-email",{to:testEmail});setStatus("Test email sent.")}catch(e){setError(e.response?.data?.error||"SMTP test failed")}}
 function exportData(){api.get("/admin/export").then(r=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(r.data,null,2)],{type:"application/json"}));a.download="donation-tracker-export.json";a.click();URL.revokeObjectURL(a.href)}).catch(e=>setError(e.response?.data?.error||"Export failed"))}
 function handleSheet(file){if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const XLSX=window.XLSX;if(!XLSX)throw new Error("Spreadsheet engine is still loading. Please try again.");const wb=XLSX.read(e.target.result,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{defval:""});setSheetRows(rows);const hs=rows.length?Object.keys(rows[0]):[];setHeaders(hs);const find=(terms)=>hs.find(h=>terms.some(t=>h.toLowerCase().replace(/[^a-z]/g,"").includes(t)))||"";setMapping({firstName:find(["firstname","fname","first"]),lastName:find(["lastname","lname","last"]),phone:find(["phone","mobile"]),email:find(["email"]),group:find(["group"]),active:find(["active","status"])});setStatus(`${rows.length} rows loaded. Map the columns and import.`)}catch(err){setError("Could not read the sheet. Use CSV or XLSX.")}};reader.readAsArrayBuffer(file)}
 async function importData(){setError("");try{const r=await api.post("/admin/import",{rows:sheetRows,mapping});setStatus(`Import complete: ${r.data.created} contacts imported.`);setSheetRows([])}catch(e){setError(e.response?.data?.error||"Import failed")}}
 async function changePassword(e){e.preventDefault();if(newPassword!==confirmPassword){setError("New passwords don't match");return}try{await api.put("/auth/change-password",{currentPassword,newPassword});setStatus("Password updated.");setCurrentPassword("");setNewPassword("");setConfirmPassword("")}catch(e){setError(e.response?.data?.error||"Could not update password")}}
 const account=<div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 max-w-md"><h2 className="font-semibold text-gray-800 mb-4">Change Password</h2><form onSubmit={changePassword}><Field label="Current password"><input type="password" required value={currentPassword} className={inputCls} onChange={e=>setCurrentPassword(e.target.value)}/></Field><Field label="New password"><input type="password" required minLength={6} value={newPassword} className={inputCls} onChange={e=>setNewPassword(e.target.value)}/></Field><Field label="Confirm new password"><input type="password" required value={confirmPassword} className={inputCls} onChange={e=>setConfirmPassword(e.target.value)}/></Field><PrimaryButton>Update Password</PrimaryButton></form></div>;
 return <Layout><div className="max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-semibold text-gray-800">{mainAdminOnly?"Main Admin Settings":"Account Settings"}</h1><p className="text-sm text-gray-500 mt-1">{mainAdminOnly?"Control email, payment, import/export and sensitive administrator settings.":"Manage your account."}</p></div>{error&&<p className="mb-4 text-sm text-red-600 bg-red-50 p-3 rounded-xl">{error}</p>}{status&&<p className="mb-4 text-sm text-green-700 bg-green-50 p-3 rounded-xl">{status}</p>}
 {!mainAdminOnly&&account}
 {mainAdminOnly&&isMain&&<>
 <form onSubmit={saveAll} className="grid lg:grid-cols-2 gap-6">
  <div className="bg-white rounded-2xl border shadow-sm p-6"><h2 className="text-lg font-semibold">Gmail Email</h2><p className="text-sm text-gray-500 mt-1 mb-5">Use your Google account and App Password. Gmail SMTP uses smtp.gmail.com with SSL on port 465. urlGoogle SMTP setuphttps://support.google.com/a/answer/176600</p><Field label="Google Account"><input type="email" required value={smtp.smtp_google_account||""} className={inputCls} onChange={e=>setSmtp({...smtp,smtp_google_account:e.target.value})}/></Field><Field label="Google App Password"><input type="password" placeholder="16-character App Password" value={smtp.smtp_app_password||""} className={inputCls} onChange={e=>setSmtp({...smtp,smtp_app_password:e.target.value})}/></Field><Field label="Email address to send from"><input type="email" required value={smtp.smtp_from_email||""} className={inputCls} onChange={e=>setSmtp({...smtp,smtp_from_email:e.target.value})}/></Field><Field label="Name to display"><input required value={smtp.smtp_display_name||""} className={inputCls} onChange={e=>setSmtp({...smtp,smtp_display_name:e.target.value})}/></Field><label className="flex items-center gap-2 text-sm mb-4"><input type="checkbox" checked={sola.lock_main_admin===true||sola.lock_main_admin==="true"} onChange={e=>setSola({...sola,lock_main_admin:e.target.checked})}/> Prevent non-Main Admins from changing Main Admin status</label><PrimaryButton>Save Settings</PrimaryButton></div>
  <div className="bg-white rounded-2xl border shadow-sm p-6"><h2 className="text-lg font-semibold">Test Email</h2><p className="text-sm text-gray-500 mt-1 mb-5">Send a real test message using the saved Gmail settings.</p><Field label="Test email address"><input type="email" value={testEmail} className={inputCls} onChange={e=>setTestEmail(e.target.value)} placeholder="you@example.com"/></Field><button type="button" onClick={sendTest} className="px-4 py-2.5 rounded-xl bg-gray-900 text-white font-semibold">Send Test Email</button><div className="mt-6 pt-5 border-t"><h3 className="font-semibold">Sola Payments</h3><p className="text-sm text-gray-500 mt-1 mb-4">The public iFields key is used in the browser; the API key stays on the server.</p><Field label="Sola API Key"><input type="password" placeholder="Leave blank to keep current key" value={sola.sola_api_key||""} className={inputCls} onChange={e=>setSola({...sola,sola_api_key:e.target.value})}/></Field><Field label="Sola iFields Public Key"><input value={sola.sola_ifields_key||""} className={inputCls} onChange={e=>setSola({...sola,sola_ifields_key:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Environment"><select value={sola.sola_environment||"production"} className={inputCls} onChange={e=>setSola({...sola,sola_environment:e.target.value})}><option value="sandbox">Sandbox</option><option value="production">Production</option></select></Field><Field label="iFields version"><input value={sola.sola_ifields_version||"2.9.2109.2701"} className={inputCls} onChange={e=>setSola({...sola,sola_ifields_version:e.target.value})}/></Field></div></div></div>
 </form>
 <div className="grid lg:grid-cols-2 gap-6 mt-6"><div className="bg-white rounded-2xl border shadow-sm p-6"><h2 className="text-lg font-semibold">Import Data</h2><p className="text-sm text-gray-500 mt-1 mb-4">Upload a CSV or Excel sheet, preview it, map the columns, then import.</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>handleSheet(e.target.files?.[0])} className="block w-full text-sm mb-4"/>{headers.length>0&&<div className="grid grid-cols-2 gap-2 mb-4">{Object.entries(mapping).map(([key,val])=><label key={key} className="text-xs text-gray-500 capitalize">{key}<select value={val} onChange={e=>setMapping({...mapping,[key]:e.target.value})} className="mt-1 w-full border rounded-lg px-2 py-2 text-sm"> <option value="">Not mapped</option>{headers.map(h=><option key={h} value={h}>{h}</option>)}</select></label>)}</div>}{sheetRows.length>0&&<><p className="text-sm text-gray-600 mb-3">Preview: {sheetRows.length} rows</p><div className="max-h-48 overflow-auto border rounded-xl"><table className="min-w-full text-xs"><tbody>{sheetRows.slice(0,5).map((r,i)=><tr key={i} className="border-b">{headers.slice(0,6).map(h=><td key={h} className="px-2 py-2 whitespace-nowrap">{String(r[h])}</td>)}</tr>)}</tbody></table></div><button type="button" onClick={importData} className="mt-4 bg-brand-600 text-white px-4 py-2.5 rounded-xl font-semibold">Import {sheetRows.length} Rows</button></>}</div><div className="bg-white rounded-2xl border shadow-sm p-6"><h2 className="text-lg font-semibold">Export Data</h2><p className="text-sm text-gray-500 my-2">Download contacts, groups, users, and donations as a backup.</p><PrimaryButton type="button" onClick={exportData}>Export System Data</PrimaryButton></div></div>
 </>}
 {mainAdminOnly&&!isMain&&<div className="bg-red-50 border border-red-100 rounded-2xl p-5 text-red-700">Main Admin permission is required.</div>}</div></Layout>;
}
