import React, { useMemo, useState } from "react";

function keyFor(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`}
function hebrewDate(d){try{return new Intl.DateTimeFormat("en-US-u-ca-hebrew",{day:"numeric",month:"long",year:"numeric"}).format(new Date(d))}catch{return ""}}
export default function DonationCalendar({donations=[]}){
  const today=new Date(); const [cursor,setCursor]=useState(new Date(today.getFullYear(),today.getMonth(),1)); const [selected,setSelected]=useState(null);
  const days=useMemo(()=>{const start=new Date(cursor.getFullYear(),cursor.getMonth(),1);const offset=start.getDay();const count=new Date(cursor.getFullYear(),cursor.getMonth()+1,0).getDate();const cells=[];for(let i=0;i<offset;i++)cells.push(null);for(let day=1;day<=count;day++)cells.push(new Date(cursor.getFullYear(),cursor.getMonth(),day));while(cells.length%7)cells.push(null);return cells},[cursor]);
  const byDay=useMemo(()=>{const m={};donations.forEach(d=>{const k=keyFor(d.date);(m[k] ||= []).push(d)});return m},[donations]);
  const selectedDonations=selected?byDay[selected]||[]:[];
  const monthTotal=donations.filter(d=>{const x=new Date(d.date);return x.getFullYear()===cursor.getFullYear()&&x.getMonth()===cursor.getMonth()}).reduce((s,d)=>s+Number(d.amount||0),0);
  return <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
    <div className="p-4 border-b flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h3 className="font-semibold text-gray-800">Donation Calendar</h3><p className="text-sm text-gray-500">${monthTotal.toLocaleString(undefined,{minimumFractionDigits:2})} raised this month</p></div><div className="flex items-center gap-2"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))} className="px-3 py-1.5 border rounded-lg">‹</button><span className="font-medium min-w-32 text-center">{cursor.toLocaleString(undefined,{month:"long",year:"numeric"})}</span><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))} className="px-3 py-1.5 border rounded-lg">›</button></div></div>
    <div className="grid grid-cols-7 text-xs font-semibold text-gray-400 border-b">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x} className="p-2 text-center">{x}</div>)}</div>
    <div className="grid grid-cols-7">{days.map((d,i)=>{if(!d)return <div key={i} className="min-h-28 border-b border-r bg-gray-50/50"/>;const k=keyFor(d), list=byDay[k]||[], total=list.reduce((s,x)=>s+Number(x.amount||0),0), isSel=selected===k;return <button key={k} onClick={()=>setSelected(isSel?null:k)} className={`min-h-28 border-b border-r p-2 text-left hover:bg-brand-50 ${isSel?"bg-brand-50 ring-1 ring-inset ring-brand-300":""}`}><div className="flex justify-between"><span className="font-semibold text-gray-700">{d.getDate()}</span>{list.length>0&&<span className="text-[10px] rounded-full bg-brand-100 text-brand-700 px-1.5 py-0.5">{list.length}</span>}</div><p className="text-[10px] text-gray-400 mt-1">{hebrewDate(d)}</p>{list.length>0&&<p className="text-xs font-semibold text-brand-700 mt-2">${total.toLocaleString(undefined,{minimumFractionDigits:2})}</p>}</button>})}</div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40" onClick={()=>setSelected(null)}><div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] overflow-hidden" onClick={e=>e.stopPropagation()}><div className="p-5 border-b flex justify-between items-start"><div><h4 className="font-semibold text-gray-800">{new Date(selected+"T12:00:00").toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h4><p className="text-sm text-gray-500">{hebrewDate(selected+"T12:00:00")}</p></div><button onClick={()=>setSelected(null)} className="text-sm text-gray-500 hover:text-gray-800">Close</button></div><div className="p-5 overflow-y-auto max-h-[65vh]"><div className="divide-y border rounded-xl overflow-hidden">{selectedDonations.map(d=><div key={d.id} className="p-3 flex justify-between gap-3"><div><p className="text-sm font-medium">{d.contact?.firstName} {d.contact?.lastName}</p><p className="text-xs text-gray-400">{d.group?.name||""}{d.campaign?` · ${d.campaign.name}`:""} · {d.type}</p></div><b className="text-brand-700">${Number(d.amount||0).toLocaleString(undefined,{minimumFractionDigits:2})}</b></div>)}</div></div></div></div>}
  </div>
}
